### ISSUE TITLE
🚀 Feature: Add stop button in chatbot to play/pause text to speech response from bot

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kom-senapati/bot-verse#267] opened 2024-11-04 16:51 UTC
### 🔖 Feature description

- Add stop button in chatbot to play/pause text to speech response from bot

### 🎤 Why is this feature needed ?

- There no button to stop response speech

### ✌️ How do you aim to achieve this?

- Add stop button

### 🔄️ Additional Information

![s1](https://github.com/user-attachments/assets/68067974-e915-4934-8fb4-f2a2e7a46e4e)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kom-senapati** [comment] 2024-11-04 16:58
Its a duplicate of #265

**Closed by kom-senapati** 2024-11-04 16:58 UTC

**Comment by mehul-m-prajapati** [comment] 2024-11-04 17:00
@kom-senapati  : It is a bit different. I want to add stop button to stop the speech response.

The other issue is about toggle between text/speech response.

**Comment by kom-senapati** [comment] 2024-11-05 02:24
I talked with him its the same thing

**Comment by mehul-m-prajapati** [comment] 2024-11-05 02:28
okay, thanks
