### ISSUE TITLE
[BUG] Sign up is not working as expected

### ISSUE THREAD

**Issue by priyanshuverma-dev** [kom-senapati/bot-verse#98] opened 2024-10-14 12:21 UTC
- sign up form is giving error 
![image](https://github.com/user-attachments/assets/49ca1306-99a5-44e5-9509-84fe30676235)

**Comment by priyanshuverma-dev** [comment] 2024-10-14 12:21
@kom-senapati Please assign this issue to me

**Comment by parteekxo** [comment] 2024-10-14 12:31
> @kom-senapati Please assign this issue to me

the issue is solved waiting to be merged

**Comment by priyanshuverma-dev** [comment] 2024-10-14 12:44
@parteekxo Thanks for updating

**Closed** 2024-10-14 12:45 UTC
